services:
  apache:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./logs:/usr/local/apache2/logs/
      - ./ssl:/usr/local/apache2/conf/ssl
    depends_on:
      - php
    networks:
      - appnet

  php:
    image: php:8.2-fpm
    container_name: php_fpm
    volumes:
      - ./html:/var/www/html
    networks:
      - appnet
	  
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: richardp
      POSTGRES_PASSWORD: Password1!
      POSTGRES_DB: postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  appnet:
  
volumes:
  pgdata:
  appnet:
