ServerName localhost

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
LoadModule rewrite_module modules/mod_rewrite.so

DocumentRoot "/usr/local/apache2/htdocs"
DirectoryIndex index.php index.html

<Directory "/usr/local/apache2/htdocs">
    AllowOverride All
    Require all granted
</Directory>

<FilesMatch "\.php$">
    SetHandler "proxy:fcgi://php:9000"
</FilesMatch>
