ServerName localhost

# Core modules required for Apache to start
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule dir_module modules/mod_dir.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule authz_core_module modules/mod_authz_core.so

# Modules required for PHP-FPM
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

DocumentRoot "/usr/local/apache2/htdocs"
DirectoryIndex index.php index.html

#<Directory "/usr/local/apache2/htdocs">
 #   AllowOverride All
 #   Require all granted
#</Directory>

<FilesMatch "\.php$">
    SetHandler "proxy:fcgi://php:9000"
</FilesMatch>
